In [1]:
import pandas as pd
import random
import datetime
from datetime import datetime, timedelta

In [47]:
num_productos = 10
num_categorias = 6

class Producto:
    def __init__(self, nombre, categoria, precio):
        self.nombre = nombre
        self.categoria = categoria
        self.precio = precio

def generar_lista_productos(num_productos):
    productos = []
    count = 0
    for j in range(num_categorias):
        for i in range(num_productos):
            count = count + 1
            producto_x = Producto(nombre=f"P_0{count}",categoria= f"{chr(ord('A') + j)}",precio=round(random.uniform(8, 20),2))
            productos.append(producto_x)       
    return productos

productos = generar_lista_productos(num_productos)

sucursales = ["Norte", "Sur", "Este", "Oeste"]

fecha_inicio = datetime(2021, 1, 1)
fecha_fin = datetime(2023, 12, 31)

data = []

for i in range((fecha_fin - fecha_inicio).days + 1):
    fecha_actual = fecha_inicio + timedelta(days=i)
    for j in sucursales:
        for h in productos:   
            fecha = fecha_actual
            prod = h.nombre
            cat = h.categoria
            precio_unitario = h.precio
            
            if(random.randint(0, 3)==0):
                cant = 0
            else:
                cant = round(random.randint(1,20)*(1 + fecha_actual.month/12) * (1 - fecha_actual.day/32), 0) 
            monto_dia = round((precio_unitario * cant),0)
            sucursal = j
            empleado = f"{chr(ord('A') + sucursales.index(j))}_{random.randint(1,8)}"
            data.append((fecha,prod,cat,precio_unitario,cant,monto_dia,sucursal,empleado))
df = pd.DataFrame(data, columns=["fecha","producto","categoria", "precio_unitario", "cantidad", "monto", "sucursal","empleado"])
df['cantidad'] = df['cantidad'].astype(int)
df['monto'] = df['monto'].astype(int)
df = df[df['cantidad'] >0]
df.to_csv('ventas.csv',index=False)

In [46]:
df.shape

(189487, 8)

In [27]:
import pandas as pd
import numpy as np

# Definir el número de filas que deseas generar
num_filas = 100

# Generar datos aleatorios para cada columna
fechas = pd.to_datetime(pd.date_range(start='2023-01-01', end='2023-12-31', periods=num_filas))
id_productos = np.random.randint(1, 1000, size=num_filas)
nombres_productos = np.random.choice(['Producto A', 'Producto B', 'Producto C'], size=num_filas)
cantidades_vendidas = np.random.randint(1, 100, size=num_filas)
precios_unitarios = np.random.uniform(10, 100, size=num_filas).round(2)
total_ventas = cantidades_vendidas * precios_unitarios
id_clientes = np.random.randint(1, 500, size=num_filas)
nombres_clientes = ['Cliente_' + str(i) for i in range(1, num_filas+1)]
id_vendedores = np.random.randint(1, 10, size=num_filas)
nombres_vendedores = ['Vendedor_' + str(i) for i in range(1, num_filas+1)]
regiones = np.random.choice(['Norte', 'Sur', 'Este', 'Oeste'], size=num_filas)
canales_venta = np.random.choice(['En línea', 'En tienda', 'Por teléfono'], size=num_filas)

# Crear el DataFrame
data = {
    'Fecha': fechas,
    'ID_Producto': id_productos,
    'Nombre_Producto': nombres_productos,
    'Cantidad_Vendida': cantidades_vendidas,
    'Precio_Unitario': precios_unitarios,
    'Total_Venta': total_ventas,
    'ID_Cliente': id_clientes,
    'Nombre_Cliente': nombres_clientes,
    'ID_Vendedor': id_vendedores,
    'Nombre_Vendedor': nombres_vendedores,
    'Region': regiones,
    'Canal_Venta': canales_venta
}

df = pd.DataFrame(data)
df.to_csv
# Mostrar las primeras filas del DataFrame generado
df.head()

,Fecha,ID_Producto,Nombre_Producto,Cantidad_Vendida,Precio_Unitario,Total_Venta,ID_Cliente,Nombre_Cliente,ID_Vendedor,Nombre_Vendedor,Region,Canal_Venta
0,2023-01-01 00:00:00.000000000,900,Producto B,20,80.98,1619.60,351,Cliente_1,1,Vendedor_1,Sur,Por teléfono
1,2023-01-04 16:14:32.727272727,464,Producto B,92,15.98,1470.16,332,Cliente_2,5,Vendedor_2,Oeste,En tienda
2,2023-01-08 08:29:05.454545454,53,Producto C,58,51.32,2976.56,184,Cliente_3,3,Vendedor_3,Oeste,En línea
3,2023-01-12 00:43:38.181818181,652,Producto B,4,64.00,256.00,462,Cliente_4,4,Vendedor_4,Este,En tienda
4,2023-01-15 16:58:10.909090909,791,Producto B,53,86.76,4598.28,357,Cliente_5,3,Vendedor_5,Este,En tienda

In [4]:
df.head(20)

,Fecha,ID_Producto,Nombre_Producto,Cantidad_Vendida,Precio_Unitario,Total_Venta,ID_Cliente,Nombre_Cliente,ID_Vendedor,Nombre_Vendedor,Region,Canal_Venta
0,2023-01-01 00:00:00.000000000,292,Producto A,78,39.029484,3044.299756,299,Cliente_1,9,Vendedor_1,Sur,En línea
1,2023-01-04 16:14:32.727272727,625,Producto C,13,14.339572,186.414437,363,Cliente_2,9,Vendedor_2,Norte,En tienda
2,2023-01-08 08:29:05.454545454,762,Producto A,48,86.914859,4171.913235,322,Cliente_3,4,Vendedor_3,Norte,Por teléfono
3,2023-01-12 00:43:38.181818181,153,Producto A,71,40.609031,2883.241170,4,Cliente_4,2,Vendedor_4,Este,En tienda
4,2023-01-15 16:58:10.909090909,227,Producto B,20,15.799498,315.989970,102,Cliente_5,4,Vendedor_5,Este,En línea
5,2023-01-19 09:12:43.636363636,380,Producto A,71,51.662466,3668.035073,5,Cliente_6,9,Vendedor_6,Este,Por teléfono
6,2023-01-23 01:27:16.363636363,384,Producto C,91,19.327092,1758.765386,282,Cliente_7,1,Vendedor_7,Oeste,Por teléfono
7,2023-01-26 17:41:49.090909090,456,Producto A,43,89.550580,3850.674944,213,Cliente_8,7,Vendedor_8,Sur,Por teléfono
8,2023-01-30 09:56:21.818181818,989,Producto B,31,85.854942,2661.503204,400,Cliente_9,5,Vendedor_9,Sur,Por teléfono
9,2023-02-03 02:10:54.545454545,926,Producto C,92,38.352494,3528.429438,3,Cliente_10,1,Vendedor_10,Oeste,En tienda
10,2023-02-06 18:25:27.272727272,994,Producto A,39,13.707217,534.581481,62,Cliente_11,3,Vendedor_11,Sur,Por teléfono
11,2023-02-10 10:40:00.000000000,262,Producto C,43,96.577698,4152.841027,87,Cliente_12,5,Vendedor_12,Norte,En tienda
12,2023-02-14 02:54:32.727272727,205,Producto C,79,78.550267,6205.471068,355,Cliente_13,9,Vendedor_13,Este,Por teléfono
13,2023-02-17 19:09:05.454545454,720,Producto B,92,33.627079,3093.691263,497,Cliente_14,5,Vendedor_14,Oeste,En línea
14,2023-02-21 11:23:38.181818181,507,Producto C,46,43.061355,1980.822314,66,Cliente_15,5,Vendedor_15,Sur,En tienda
15,2023-02-25 03:38:10.909090909,555,Producto B,66,30.381666,2005.189953,451,Cliente_16,2,Vendedor_16,Norte,En tienda
16,2023-02-28 19:52:43.636363636,645,Producto B,46,65.368907,3006.969740,62,Cliente_17,7,Vendedor_17,Norte,En tienda
17,2023-03-04 12:07:16.363636363,843,Producto A,40,79.793766,3191.750634,248,Cliente_18,2,Vendedor_18,Oeste,Por teléfono
18,2023-03-08 04:21:49.090909090,626,Producto A,53,80.468580,4264.834734,23,Cliente_19,9,Vendedor_19,Sur,En tienda
19,2023-03-11 20:36:21.818181818,204,Producto C,54,85.053995,4592.915743,5,Cliente_20,6,Vendedor_20,Oeste,En línea